name: Quality assurance

on:
  push:
    branches:
      - main

jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"

    steps:
      - uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

        # You are now able to use PDM in your workflow
      - name: Install dependencies
        run: pdm sync

      - name: Check coverage
        run: pdm run coverage run -m nose2

      - uses: eosc-synergy/sqaaas-assessment-action@v2
